# Generated by Django 4.2.16 on 2026-04-29 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(default='La plateforme est en cours de maintenance. Merci de reessayer dans quelques instants.')),
                ('maintenance_start', models.DateTimeField(blank=True, null=True)),
                ('estimated_end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
            },
        ),
    ]
