# Generated by Django 4.2.16 on 2026-04-05 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chatbot", "0002_chatmessage_duration_seconds_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("well_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("PRODUCTION", "Production"),
                            ("BUDGET", "Budget / Coûts"),
                            ("WORKOVER", "Workover / Interventions"),
                            ("RESERVOIR", "Réservoir"),
                            ("GENERAL", "Général"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(max_length=200)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Mémoire utilisateur",
                "verbose_name_plural": "Mémoires utilisateur",
                "ordering": ["-updated_at"],
                "unique_together": {("user", "well_code", "topic")},
            },
        ),
    ]
