# Generated by Django 4.2.16 on 2026-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0006_sessionshare"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="analysiscomment",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Analysis comment",
                "verbose_name_plural": "Analysis comments",
            },
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Chat session",
                "verbose_name_plural": "Chat sessions",
            },
        ),
        migrations.AlterModelOptions(
            name="sessionshare",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Session share",
                "verbose_name_plural": "Session shares",
            },
        ),
        migrations.AlterModelOptions(
            name="usermemory",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "User memory",
                "verbose_name_plural": "User memories",
            },
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(default="New conversation", max_length=200),
        ),
        migrations.AlterField(
            model_name="usermemory",
            name="topic",
            field=models.CharField(
                choices=[
                    ("PRODUCTION", "Production"),
                    ("BUDGET", "Budget / Costs"),
                    ("WORKOVER", "Workover / Interventions"),
                    ("RESERVOIR", "Reservoir"),
                    ("GENERAL", "General"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
    ]
