# Generated by Django 4.2.16 on 2026-05-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0007_alter_analysiscomment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="chart_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
