# Generated by Django 4.2.16 on 2026-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfile",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Uploaded file",
                "verbose_name_plural": "Uploaded files",
            },
        ),
        migrations.AlterField(
            model_name="uploadedfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Completed"),
                    ("error", "Error"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
