# Generated by Django 4.2.16 on 2026-05-20 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_alter_uploadedfile_options_alter_uploadedfile_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("success", "Completed"),
                    ("error", "Error"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
