# Generated by Django 4.2.16 on 2026-04-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("UPLOAD_FILE", "Upload file"),
                    ("CHATBOT_QUESTION", "Chatbot question"),
                    ("EXPORT_PDF", "Export PDF"),
                    ("EXPORT_EXCEL", "Export Excel"),
                    ("VIEW_PAGE", "View page"),
                    ("DELETE_SESSION", "Delete session"),
                    ("SESSION_EXPIRED", "Session expired"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
