# Generated by Django 4.2.16 on 2026-04-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('well_code', models.CharField(blank=True, default='', max_length=32)),
                ('anomaly_type', models.CharField(blank=True, default='', max_length=120)),
                ('severity', models.CharField(blank=True, default='', max_length=40)),
                ('description', models.TextField(blank=True, default='')),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(blank=True, default='', max_length=40)),
            ],
            options={
                'verbose_name': 'Anomalie',
                'verbose_name_plural': 'Anomalies',
                'ordering': ['-detected_at'],
            },
        ),
    ]
